#!/usr/bin/env bash
#
# Script to manage links.
# You need github.com/junegunn/fzf to use this script.
#
# To list available commands, type 'lnk help'.


if [ -z "$XDG_DATA_HOME" ]; then
    PREFIX="$HOME/.link-store"
else
    PREFIX="$XDG_DATA_HOME/link-store"
fi

STORAGE="${PREFIX}/links.tsv"


cmd_usage() {
    cat <<-_EOF
Usage:
    $PROGRAM init
        Initialize the link store.
    $PROGRAM find [--no-browser,-n]
        Launches FZF to search for a link and open it in the browser.
        If --no-browser is specified, the link is copied to the clipboard instead.
    $PROGRAM insert link-address
        Insert a new link.
    $PROGRAM git git-command-args...
        Execute a git command specified by git-command-args, e.g. '$PROGRAM git push'
    $PROGRAM help
        Show this text.
	_EOF
}

die() {
    echo "$@" >&2
    exit 1
}

if_initialized() {
    git -C "$PREFIX" rev-parse --is-inside-work-tree > /dev/null 2>&1 ||
    die "Git repository not initialized in $PREFIX. Run '$PROGRAM init' first."
}

git_add_commit() {
    git -C "$PREFIX" add $(basename "$STORAGE")
    git -C "$PREFIX" commit -m "$1"
}

cmd_init() {
    [ ! -z "$1" ] && die "Usage: $PROGRAM $COMMAND"

    mkdir -p "$PREFIX"

    if git -C "$PREFIX" rev-parse --is-inside-work-tree > /dev/null 2>&1; then
        echo "Git repository already initialized in $PREFIX"
    else
        git -C "$PREFIX" init
        echo -e "link\ttags\tdate" > "$STORAGE"
        git_add_commit "Initialize link store"
        echo "FZF should be installed to use this script. Try 'brew install fzf' or 'apt install fzf'."
    fi

    echo "If you want to connect a remote repository, run '$PROGRAM git remote add origin remote-repo-url'."
}

cmd_git() {
    if_initialized
    git -C "$PREFIX" "$@"
}

cmd_insert() {
    if_initialized
    [ -z "$1" ] || [ ! -z "$2" ] && die "Usage: $PROGRAM $COMMAND link-address"

    local link="$1"
    local date=$(date +%Y-%m-%d\ %H:%M)
    read -p "Tags (split by space): " tags && tags=$(echo "$tags" | tr -s ' ')

    sed -i "1 a $link\t$tags\t$date" "$STORAGE"
    git_add_commit "Add link $link"
}

cmd_find() {
    if_initialized

	local opts no_browser=0
	opts="$(getopt -o n -l no-browser -n "$PROGRAM" -- "$@")"
    [ $? -ne 0 ] && die "Usage: $PROGRAM $COMMAND [--no-browser,-n]"

	eval set -- "$opts"
	while true; do case $1 in
		-n|--no-browser) no_browser=1; shift ;;
		--) shift; break ;;
	esac done

    [ ! -z "$1" ] && die "Usage: $PROGRAM $COMMAND [--no-browser,-n]"

    local link=$(
        cat "$STORAGE" |
        column -s $'\t' --table-order 3,2,1 -t |
        fzf --height 50% --reverse --border rounded --header-lines 1 |
        rev | cut -d' ' -f1 | rev
    )
    [ -z "$link" ] && die "No link selected"

    [[ $link == http* ]] || link="http://$link"

    if [ "$(uname)" == "Linux" ]; then
        echo -n "$link" | xclip -selection clipboard
        [ $no_browser -eq 0 ] && xdg-open "$link"
    elif [ "$(uname)" == "Darwin" ]; then
        echo -n "$link" | pbcopy
        [ $no_browser -eq 0 ] && open "$link"
    else
        die "$(uname) is not supported. Link: $link"
    fi

    echo "Copied link to clipboard: $link"
}


PROGRAM="${0##*/}"
COMMAND="$1"

case "$1" in
    init)        shift; cmd_init "$@" ;;
    help|--help) shift; cmd_usage "$@" ;;
    insert|add)  shift; cmd_insert "$@" ;;
    find|search) shift; cmd_find "$@" ;;
    git)         shift; cmd_git "$@" ;;
    *)                  cmd_usage "$@" ;;
esac

exit 0
